### ISSUE TITLE
 部署了你编译好的，页面无法显示。！！

### ISSUE THREAD

**Issue by iibrat** [nangcr/chatgpt-aws-proxy#3]
![微信图片_20230331230423](https://user-images.githubusercontent.com/108867675/229158138-ee81e7fd-3933-419c-827d-090af5bee8ae.png)

部署了你编译好的，页面无法显示。！！

**Comment by nangcr** [comment]
这个项目是为API调用做代理使用的。使用方法请参考 [OpenAI 官方文档](https://platform.openai.com/docs/api-reference)
